#!/bin/sh
if test x$1 = x-g; then
   shift;
   (cd $1; /brew/bin/doxygen -g)
fi
(cd $1; sed -i -e 's/GENERATE_XML.*=.*NO/GENERATE_XML = YES/' $2)
(cd $1; /brew/bin/doxygen $2)
if test x$4 = x; then
  xml=`pwd`/$1/xml
else
  xml=$4
fi
mono `dirname $0`/DoxyToEcma.exe $3 $xml