#!/bin/sh
if test x$1 = x-g; then
   shift;
   (cd $1; /brew/bin/doxygen -g)
fi
sed -i 's/GENERATE_XML.*=NO/GENERATE_XML = YES/' $2
(cd $1; /brew/bin/doxygen)
mono `dirname $0`/DoxyToEcma.exe $3 `pwd`/$1/xml