
Couchbase.dll: libCouchCocoa.a libTouchDB.a bin/Debug/Couchbase.dll
	/Applications/MonoDevelop.app/Contents/MacOS/mdtool build
	cp bin/Debug/Couchbase.dll .

foo:
	git clone git://github.com/couchbaselabs/TouchDB-iOS.git
	(cd TouchDB-iOS; git submodule init; git submodule update)


