#### Sample Builder
#### Author: Alex Soto alex.soto@xamarin.com

MDTOOL=/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool

#If you hapen to add a sample please add it here so it is easier to test if it builds

all:
	#$(MDTOOL) build -c:"Release|iPhone" Sample/Sample.sln
	
clean:
	#$(MDTOOL) build -c:"Release|iPhone" -t:Clean Sample/Sample.sln
