#### Sample Builder
#### Author: Alex Soto alex.soto@xamarin.com

MDTOOL=/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool

all:
	$(MDTOOL) build -c:"Release|iPhone" BeeblexDemo.sln
	
clean:
	$(MDTOOL) build -c:"Release|iPhone" -t:Clean BeeblexDemo.sln
